/** Small, dependency-free Chinese UI translation layer for the terminal client. */
const TRANSLATIONS: ReadonlyArray<readonly [string, string]> = [
	["Welcome back!", "欢迎回来！"],
	["Tip: ", "提示："],
	["Tips", "使用提示"],
	[" for prompt actions", " 执行提示操作"],
	[" for commands", " 执行命令"],
	[" to run bash", " 执行 Bash"],
	[" to run python", " 执行 Python"],
	["LSP Servers", "LSP 服务器"],
	["Recent sessions", "最近会话"],
	["No recent sessions", "暂无最近会话"],
	["No LSP servers", "暂无 LSP 服务器"],
	["Preview:", "预览："],
	["Preview", "预览"],
	["Setup saved", "设置已保存"],
	["Handing off to the normal CLI…", "正在进入主程序…"],
	["press enter to skip", "按回车跳过"],
	["paused for ", "已暂停 "],
	["esc to resume", "按 Esc 恢复"],
	["resume", "恢复"],
	["Main agent, subagents, and advisor hold at their next step.", "主代理、子代理和顾问将在下一步暂停。"],
	["In-flight calls finish; nothing new starts until you resume.", "正在执行的调用会完成；恢复前不会开始新的任务。"],
	["esc · enter · space — resume", "Esc · 回车 · 空格键  恢复"],
	["Enter to save · Esc to cancel · Clear field to unset", "回车保存 · Esc 取消 · 清空输入以取消设置"],
	["Cancel", "取消"],
	["Confirm", "确认"],
	["Clear all limits", "清除所有限制"],
	["Make every provider unlimited", "让所有服务提供商不受限制"],
	["(preview not available)", "（预览不可用）"],
	["Appearance", "外观"],
	["Model", "模型"],
	["Interaction", "交互"],
	["Context", "上下文"],
	["Memory", "记忆"],
	["Files", "文件"],
	["Shell", "Shell"],
	["Tools", "工具"],
	["Tasks", "任务"],
	["Providers", "服务商"],
	["Theme", "主题"],
	["Composer", "输入框"],
	["Status Line", "状态栏"],
	["Display", "显示"],
	["Images", "图像"],
	["Thinking", "思考"],
	["Sampling", "采样"],
	["Prompt", "提示词"],
	["Retry & Fallback", "重试与备用方案"],
	["Advisor", "顾问"],
	["Prewalk", "预扫描"],
	["Vision", "视觉"],
	["Input", "输入"],
	["Approvals", "审批"],
	["Notifications", "通知"],
	["Speech", "语音"],
	["Collab", "协作"],
	["Magic Keywords", "魔法关键词"],
	["Startup & Updates", "启动与更新"],
	["Power (macOS)", "电源（macOS）"],
	["Agent", "代理"],
	["Git", "Git"],
	["General", "常规"],
	["Compaction", "压缩"],
	["Rules (TTSR)", "规则（TTSR）"],
	["Experimental", "实验功能"],
	["Auto-Learn", "自动学习"],
	["Mnemopi", "Mnemopi"],
	["Hindsight", "Hindsight"],
	["Editing", "编辑"],
	["Reading", "读取"],
	["Read Summaries", "读取摘要"],
	["Bash", "Bash"],
	["Eval & Runtimes", "执行与运行时"],
	["Available Tools", "可用工具"],
	["Todos", "待办事项"],
	["Grep & Browser", "搜索与浏览器"],
	["Computer", "电脑控制"],
	["GitHub", "GitHub"],
	["Output Limits", "输出限制"],
	["Execution", "执行"],
	["Discovery & MCP", "发现与 MCP"],
	["Extensions", "扩展"],
	["Developer", "开发者"],
	["Modes", "模式"],
	["Subagents", "子代理"],
	["Isolation", "隔离"],
	["Commands & Skills", "命令与技能"],
	["Services", "服务"],
	["Fireworks", "Fireworks"],
	["Tiny Model", "轻量模型"],
	["Protocol", "协议"],
	["Timeouts", "超时"],
	["Privacy", "隐私"],
	["Rounded Box (Default)", "圆角框（默认）"],
	["Top Rule Dock", "顶部规则栏"],
	["Compact Field", "紧凑输入栏"],
	["Accent Rail", "强调色轨道"],
	["Borderless", "无边框"],
	["Full-width horizontal rules above and below, status line at bottom", "上下使用全宽横线，状态栏位于底部"],
	["Status line embedded in top border, compact 2-line prompt", "状态栏嵌入顶部边框，紧凑的两行输入框"],
	["Framed horizontal rules with status line at bottom", "带边框横线，状态栏位于底部"],
	["Clean prompt glyph with status line at bottom, no box borders", "简洁的提示符，状态栏位于底部，不显示边框"],
	["Single top rule with status docked onto it and below", "单条顶部横线，状态栏停靠在横线上及下方"],
	["Filled one-row field with accent end caps", "带强调色端点的单行填充输入栏"],
	["Filled one-row field anchored by a single accent rail", "由单条强调色轨道固定的单行填充输入栏"],
	["Off", "关闭"],
	["On", "开启"],
	["Default", "默认"],
	["Custom", "自定义"],
	["Minimal", "最简"],
	["Compact", "紧凑"],
	["Full", "完整"],
	["None", "无"],
	["Unicode", "Unicode"],
	["Nerd Font", "Nerd Font 字体"],
	["Maximum compatibility", "最大兼容性"],
	["Requires Nerd Font", "需要 Nerd Font 字体"],
	["No special characters", "不使用特殊字符"],
	["Auto Resume", "自动恢复"],
	["Sleep Prevention", "防止休眠"],
	["Prevent Idle Sleep", "防止闲置休眠"],
	["Prevent Display Sleep", "防止显示器休眠"],
	["Prevent System Sleep", "防止系统休眠"],
	["Enable Advisor", "启用顾问"],
	["Enable Prewalk", "启用预扫描"],
	["Enable Git Integration", "启用 Git 集成"],
	["Max In-Flight Requests", "最大并发请求数"],
	["Global", "全局"],
	["Per-project", "按项目"],
	["Dark Theme", "深色主题"],
	["Light Theme", "浅色主题"],
	["Symbol Preset", "符号方案"],
	["Color-Blind Mode", "色盲模式"],
	["Composer Shape", "输入框样式"],
	["Status Line Preset", "状态栏方案"],
	["Status Line Separator", "状态栏分隔符"],
	["Thinking Level", "思考等级"],
	["Hide Thinking Blocks", "隐藏思考块"],
	["Show Token Usage", "显示令牌用量"],
	["Show Turn Time", "显示回合耗时"],
	["Show Inline Images", "显示内嵌图像"],
	["Auto-Resize Images", "自动调整图像大小"],
	["Block Images", "阻止图像"],
	["Resize Scrollback", "调整回滚区"],
	["Append", "追加"],
	["Rebuild", "重建"],
	["Preserve", "保留"],
	["Smooth Streaming", "平滑流式输出"],
	["Hide Tool Activity", "隐藏工具活动"],
	["Setup", "设置"],
	["Choose glyph mode", "选择符号模式"],
	["Pick the row that renders cleanly in your terminal.", "选择在你的终端中显示正常的一项。"],
	["Choose your default model", "选择默认模型"],
	["Search configured models and save the model used for new sessions.", "搜索已配置的模型，并保存新会话使用的模型。"],
	["Discovering available models…", "正在发现可用模型…"],
	["Pick a theme", "选择主题"],
	["Theme changes preview live. Nothing is saved until you press Enter.", "主题会实时预览，按回车前不会保存。"],
	["Loading themes…", "正在加载主题…"],
	["Ready to use", "可以使用"],
	["Needs credentials", "需要凭据"],
	["Login cancelled.", "登录已取消。"],
	["Starting OAuth flow…", "正在启动 OAuth 流程…"],
	["Signed in to ", "已登录 "],
	["Login failed: ", "登录失败："],
	["Set up your providers", "设置服务商"],
	["Sign in and pick a web search provider. Press Esc when you're done.", "登录并选择网页搜索服务商。完成后按 Esc。"],
	["Providers", "服务商"],
	["Sign in", "登录"],
	["Web search", "网页搜索"],
	["Pick a provider to sign in — you can connect more than one.", "选择要登录的服务商，可连接多个服务商。"],
	["Open login URL", "打开登录链接"],
	["clipboard copy attempted; Alt+C retries", "已尝试复制到剪贴板；按 Alt+C 重试"],
	["Browser login: ", "浏览器登录："],
	["Local shortcut (this machine only): ", "本机快捷链接："],
	["Paste the returned code or redirect URL when prompted.", "出现提示后粘贴返回的代码或重定向 URL。"],
	["Paste the authorization code (or full redirect URL):", "粘贴授权代码（或完整重定向 URL）："],
	["Credentials saved to ", "凭据已保存到 "],
	["Choose another provider or press Esc to continue.", "请选择其他服务商，或按 Esc 继续。"],
	["Choose the provider the web_search tool should prefer.", "选择 web_search 工具优先使用的服务商。"],
	["Automatically uses the first configured provider.", "自动使用第一个已配置的服务商。"],
	["Checking availability…", "正在检查可用性…"],
	["Not configured yet — add its API key or sign in to enable it.", "尚未配置；添加 API key 或登录后即可启用。"],
	["Web search set to ", "网页搜索已设置为 "],
	["Setup step ", "设置步骤 "],
	["Select provider to login", "选择要登录的服务商"],
	["Select provider to logout", "选择要退出登录的服务商"],
];

/** Translate user-facing UI text while preserving unknown extension text. */
function escapeRegExp(text: string): string {
	return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function translateUiText(text: string): string {
	let translated = text;
	for (const [source, target] of TRANSLATIONS) {
		if (/^[A-Za-z]+$/.test(source)) {
			translated = translated.replace(new RegExp(`\\b${escapeRegExp(source)}\\b`, "g"), target);
		} else {
			translated = translated.split(source).join(target);
		}
	}
	return translated;
}

export function translateOption<T extends { label: string; description?: string }>(option: T): T {
	return {
		...option,
		label: translateUiText(option.label),
		description: option.description === undefined ? undefined : translateUiText(option.description),
	};
}
